export const REMOVE_APPLIED_FILTER_ITEM = 'REMOVE_APPLIED_FILTER_ITEM';
export const SET_APPLIED_FILTERS = 'SET_APPLIED_FILTERS';
export const REMOVE_APPLIED_FILTER_TYPE = 'REMOVE_APPLIED_FILTER_TYPE';
export const CLEAR_APPLIED_FILTERS = 'CLEAR_APPLIED_FILTERS';
